### ISSUE TITLE
Install freezing

### ISSUE THREAD

**Issue by johnnogent** [hpssjellis/google-magenta-midi-music-on-linux-hello-world#1]
Hello

install (bash setup.sh) is freezing on bazel.

Many thanks
John

**Comment by hpssjellis** [comment]
It worked about two weeks ago. I will try it again and see what I get.

**Comment by johnnogent** [comment]
many thanks, I have created a new anaconda environment from scratch, this works.

**Comment by hpssjellis** [comment]
Wow you are right!  I git cloned https://github.com/sherjilozair/char-rnn-tensorflow.git into the same directory and it works fine, so the problem is with Magenta. Took me a week to solve it only 2 weeks ago. Magenta is proving to be a bit time intensive.

**Comment by hpssjellis** [comment]
Sorry, some how I closed that issue :> 

Try

`pip freeze `

to see if pip has installed jupyter matplotlib scipy

I am retrying

`pip install jupyter matplotlib scipy`

**Comment by hpssjellis** [comment]
I am also messing around with 

pip install magenta

Mine does seem to be working now. Problem is that the above pip install does not seem to run from the main setup.sh file. Has to be run after the installation.

In the Magenta main folder try 

`pip install magenta jupyter matplotlib scipy`

**Comment by hpssjellis** [comment]
Just clued in that you solved the issue on your computer using anaconda. Have a good day.
